import timer from './modules/timer';
import menu from './modules/menu';
import modal from './modules/modal';
import smoothScroll from './modules/smoothScroll';
import validation from './modules/validation';
import slider from './modules/slider';
import tabs from './modules/tabs';
import calc from './modules/calc';
import sendForm from './modules/sendForm';
import maskPhone from './modules/maskPhone';

timer('20 september 2022');
menu();
modal();
smoothScroll();
validation();
slider('.portfolio-content', '.portfolio-item');
tabs();
calc(100);
sendForm({ formId: '#form1', someElem: [{ type: 'block', id: 'total' }] });
sendForm({ formId: '#form2' });
sendForm({ formId: '#form3' });
maskPhone('*[name="user_phone"]', '+7 (___)-___-__-__');
